// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuCmWsm5WxDImODtvqyrnN1dCCEVJ0g7c',
    appId: '1:467098722729:android:3f46bb81699cef156c64b8',
    messagingSenderId: '467098722729',
    projectId: 'qoin-8854b',
    databaseURL: 'https://qoin-8854b.firebaseio.com',
    storageBucket: 'qoin-8854b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkQDqtludmO2B346UuwAlG8-IzEcgOzsQ',
    appId: '1:467098722729:ios:3be415ab1068a2ac6c64b8',
    messagingSenderId: '467098722729',
    projectId: 'qoin-8854b',
    databaseURL: 'https://qoin-8854b.firebaseio.com',
    storageBucket: 'qoin-8854b.appspot.com',
    iosClientId: '467098722729-klb1le8ch4rf9aojoflc05kjcs7nnqjl.apps.googleusercontent.com',
    iosBundleId: 'id.inisa',
  );
}
